### ISSUE TITLE
hyst_hp listed twice in commands_hpsu_xx.csv

### ISSUE THREAD

**Issue by pdcemulator** [Spanni26/pyHPSU#17]
hyst_hp is listed twice in commands files - with different description. I suppose this means two seperate commands.

**Comment by Spanni26** [comment]
Hi,

no, its the same command. Only two different descriptions. I will delete
one.

Regards

Daniel



Am 29.03.2019 um 09:13 schrieb pdcemulator:

**Comment by Spanni26** [comment]
Fixed
