### ISSUE TITLE
value overflow qch - starting again at 0

### ISSUE THREAD

**Issue by pdcemulator** [Spanni26/pyHPSU#21]
Hello,

this is not an pyHPSU related issue, just a question to Rotex data.

The value for qch (or qwp a longer time ago) was above 32228 and is starting again at 0. So I suppose an internal numger range was overflowed but I didnt had a value logging active at this time. So I do not know the exact value to add to the current value to get the all time qch value in my system.

Has anybody an data logging active while one of his value get this overflow?

As an IT guy I would expect 32768, but I am not sure, so I am asking here for other experiences.
Thank you

**Comment by Spanni26** [comment]
Hmm, looks like the conversation into a real value gets wrong.

Will investigate this tomorrow.


Daniel


Am 10.06.2019 um 11:00 schrieb pdcemulator:

**Comment by pdcemulator** [comment]
Hi Daniel,
this is not an pyHPSU issue. Rotex device also display also values beginning with 0. So it seems that the internal number storage for this value was full and started again at 0.

**Comment by Spanni26** [comment]
Hmmm,

qch is the ammount of the generated heat. Seems to be a firmware problem
of the HPSU.



Am 10.06.2019 um 11:05 schrieb pdcemulator:
