### ISSUE TITLE
MQTT sending commands not working

### ISSUE THREAD

**Issue by Vortecsz** [Spanni26/pyHPSU#64]
Hello guys.
When i try to send a command trough mqtt i can't get it to work;

```
service: mqtt.publish
data:
topic: ALTHERMA/command/mode_01
payload: "17"
```

The pyHPSU is running like this;
`pyHPSU.py -a -o MQTT`

If i do like that it changes it
`pyHPSU.py -c mode_01:17
`

**Comment by evildad** [comment]
I think you missed the following part:
`--mqtt_daemon         set up an mqtt daemon that subscribe to a command
                        topic and executes received command on HPSU`
